[project]
name = 'civica-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Transparent-voting]
path = 'contracts/Transparent-voting.clar'
clarity_version = 3
epoch = 3.0

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 3
epoch = 3.0

[contracts.vote-counter]
path = 'contracts/vote-counter.clar'
clarity_version = 1
epoch = 2.05

[contracts.voter-registration]
path = 'contracts/voter-registration.clar'
clarity_version = 3
epoch = 3.0

[contracts.voting-process]
path = 'contracts/voting-process.clar'
clarity_version = 3
epoch = 3.0

[contracts.voting-window]
path = 'contracts/voting-window.clar'
clarity_version = 1
epoch = 2.05
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
